# Setup ClusterRoleBinding between ClusterRole and ServiceAccount.
# ClusterRoleBinding is namespace-less and must have unique name
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: clickhouse-operator-{{ include "chOperator.namespace" . }}
  namespace: {{ include "chOperator.namespace" . }}
  labels:
    clickhouse.altinity.com/chop: 0.19.0
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: clickhouse-operator-{{ include "chOperator.namespace" . }}
subjects:
- kind: ServiceAccount
  name: clickhouse-operator
  namespace: {{ include "chOperator.namespace" . }}
