# Template Parameters:
#
# COMMENT=
# NAMESPACE={{ include "chOperator.namespace" . }}
# NAME=clickhouse-operator
#
# Setup ServiceAccount
apiVersion: v1
kind: ServiceAccount
metadata:
  name: clickhouse-operator
  namespace: {{ include "chOperator.namespace" . }}
  labels:
    clickhouse.altinity.com/chop: 0.19.0