{{- if .Values.coldStorage.role.enabled }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: clickhouse-instance
  {{- with .Values.coldStorage.role.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
